[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spaghetti-hackathon"
version = "0.1.0"
authors = [
  { name="Stepan Vondracek" },
]
description = "Spaghetti Hackathon Project"
readme = "README.md"
requires-python = ">3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [    
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0",
    "pyhumps>=3.8.0",
    "google-genai",
    "pydantic",
    "python-dotenv",
    "httpx",
    "lightrag-hku",
]

[project.urls]
"Homepage" = "https://github.com/svondracek0/spaghetti-hackathon"

[tool.setuptools.packages.find]
where = ["src"]
